basePath: /api/v1
definitions:
  model.PatientData:
    properties:
      comments:
        items:
          type: string
        type: array
      date_of_birth:
        type: string
      name:
        type: string
      samples:
        items:
          $ref: '#/definitions/model.Sample'
        type: array
      sex:
        type: string
    type: object
  model.PatientList:
    properties:
      patients:
        items:
          $ref: '#/definitions/model.PatientListEntry'
        type: array
    type: object
  model.PatientListEntry:
    properties:
      date:
        type: string
      name:
        type: string
      patient_id:
        type: string
      ref_id:
        type: string
      samples:
        type: string
    type: object
  model.Sample:
    properties:
      image:
        type: string
    type: object
  model.Test:
    properties:
      amount:
        type: integer
      change:
        type: number
      date_created:
        type: string
      id:
        type: string
      usd:
        type: integer
    type: object
info:
  contact: {}
  description: This service is responsible for content delivery. Handles content delivery
    to the user
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
  title: CDN API
  version: "1.0"
paths:
  /patient-data:
    get:
      consumes:
      - application/json
      description: Checks for a matching id in the databse and returns data for that
        id
      parameters:
      - description: reference id of the samples
        in: query
        name: ref_id
        required: true
        type: string
      - description: id of the patient
        in: query
        name: patient_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.PatientData'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Provides data about a patient
      tags:
      - Patient
  /patient-list:
    get:
      consumes:
      - application/json
      description: Finds username in database and retrieves all patients for that
        user
      parameters:
      - description: username of the doctor
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.PatientList'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Retrieves a list of patients for the specified doctor username
      tags:
      - Patient
  /test-no-auth:
    get:
      consumes:
      - application/json
      description: Will ask the service to generate a test json and return it back
        to the requester
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Test'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Gets a test value from the service, sanity check
      tags:
      - Tests
swagger: "2.0"
